mysite/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
	# /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/music/71/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /music/album/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
 
     # /music/album/album/2/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/album/2/delete
    url(r'^(?P<pk>[0-9]+)/delete_album/$', views.AlbumDelete.as_view(), name='delete_album'),
    #url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls'))
]

mysite/music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class Album(models.Model):
	
	artist = models.CharField(max_length = 250)
	album_title = models.CharField(max_length = 500)
	genre = models.CharField(max_length = 100)
	album_logo = models.CharField(max_length = 1000)

	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk': self.pk})

	def __str__(self):
		representation = 'title: ' + self.album_title + ' artist:' +self.artist
		return representation
	
class Song(models.Model):

	album = models.ForeignKey(Album, on_delete = models.CASCADE)
	file_type = models.CharField(max_length = 10)
	song_title = models.CharField(max_length = 250)
	is_favorite = models.BooleanField(default = False)

	def __str__(self):
		return self.song_title

mysite/music/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from .models import Album, Song
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render,get_object_or_404

class IndexView(generic.ListView):
	
	template_name = "music/index.html"
	context_object_name = 'all_albums'
	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	
	model = Album
	template_name= 'music/detail.html'

class AlbumCreate(CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']
	
class AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

	def get_initial(self):

		initial = super(AlbumUpdate, self).get_initial()
		print('initial data', initial)
		# retrieve current object
		album_object = self.get_object()
		initial['artist'] = album_object.artist
		initial['album_title'] = album_object.album_title
		initial['genre'] = album_object.genre
		initial['album_logo'] = album_object.album_logo
		return initial

	def get_object(self, *args, **kwargs):
		album = get_object_or_404(Album, pk=self.kwargs['pk'])
		return album

class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')


#def delete_album(request, album_id):
#    album = Album.objects.get(pk=album_id)
#    album.delete()
#    albums = Album.objects.all()
#    return render(request, 'music/index.html', {'all_albums': albums})

mysite/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{%block albums_active %}active{% endblock %}

{% block body%}
<div class="container-fluid">
	
	<div class="col-sm-12 col-md-7">
		
		<div class="panel panel-default">
			
			<div class="panel-body">
				
				<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
					{% csrf_token %} 
					{% include 'music/form-template.html' %}
					<div class="form-group">
						
						<div class="col-sm-offset-2 col-sm-10">
							
							<button type="submit" class="btn btn-success">Submit</button>

						</div>

					</div>
				</form>


			</div>

		</div>

	</div>

</div>
{% endblock %}

mysite/music/templates/music/base.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Viberr{% endblock %}</title>
	<!-- Loads the path to your static file-->
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"> 
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script> 
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> 
	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>﻿
</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
		<!-- Header -->	
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
			</div>

		<!-- Items -->
			<div class="collapse navbar-collapse" id ="topNavBar">
				<ul class="nav navbar-nav">
					<li class="">
						<a href="{% url 'music:index' %}">
							<span class="glyphicon glyphicon-cd" aria-hidden="true"> </span>&nbsp;Albums
						</a>
					</li>
					<li class="">
						<a href="#">
							<span class="glyphicon glyphicon-music" aria-hidden="true"> </span>&nbsp;Songs
						</a>
					</li>
				</ul>

				<form class="navbar-form navbar-left" role="search" method="get" action="#">
					<div class="form-group">
						<input type="text" class="form-control" name="q" value="">
					</div>
					<button type="submit" class="btn btn-default"> Search
					</button>
				</form>

				<ul class="nav navbar-nav navbar-right">
					<li class="">
						<a href="{% url 'music:album-add' %}">
							<span class="glyphicon glyphicon-plus" aria-hidden="true"> </span>&nbsp; Add Album
						</a>
					</li>

					<li class="">
						<a href="#">
							<span class="glyphicon glyphicon-off" aria-hidden="true"> </span>&nbsp; Logout
						</a>
					</li>
				</ul>

			</div>
		</div>	
	</nav>
	{% block body%}
	{% endblock %}
</body>
</html>

mysite/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album detail{% endblock %}
{% block body %}
	<img src="{{ album.album_logo }}" style="width: 250px;">

	<h1>{{ album.album_title }}</h1>
	<h3>{{ album.artist }}</h3>

	{% for song in album.song_set.all %}
		{{ song.song_title }}
		{% if song.is_favorite %}
			<img src="https://www.ultimagame.es/imagen-i5554-x.jpg", style="width:15px;">		
		{% endif %}
		<br>	
	{% endfor %}
		
{% endblock %}

mysite/music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

mysite/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}

	<ul>
		{% for album in all_albums %}
		<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</li>
		<div>
            <!-- Delete Album -->
            <form action="{% url 'music:delete_album' album.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="album_id" value="{{ album.id }}" />
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-trash"></span>
                </button>
            </form>

            <!-- Update Album -->
            <form action="{% url 'music:album-update' album.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="album_id" value="{{ album.id }}" />
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-repeat"></span>
                </button>
            </form>

			</div>
		{% endfor %}
	</ul>

{% endblock %}